### ISSUE TITLE
Crash while decoding texture with internal palette data

### ISSUE THREAD

**Issue by SonicFreak94** [nickworonekin/puyotools#11]
Seems to be a regression. It works fine in the previous release, but in the current release it throws `ArgumentOutOfRangeException` in [PvrPixelCodec.DecodePixel](https://github.com/nickworonekin/puyotools/blob/d4d13e1e9fbb1b16cd79d0e73a71c4d74aac6052/Libraries/VrSharp/PvrTexture/PvrPixelCodec.cs#L62).

With the specific PVR I'm testing (attached), `sourceIndex` is the same as `source.Length`.

[SSTX_BODY.zip](https://github.com/nickworonekin/puyotools/files/641030/SSTX_BODY.zip)

**Comment by nickworonekin** [comment]
This is fixed in the 2.0.3 release.
