### ISSUE TITLE
MRG Extraction

### ISSUE THREAD

**Issue by Jezreep** [nickworonekin/puyotools#13]
Hey how can I extract the MRG files?

**Comment by nickworonekin** [comment]
You can use the archive extractor and add the MRG file, or use the archive explorer and open the MRG file. Note that only MRG files from Puyo Puyo Fever 2 are supported.

**Comment by Jezreep** [comment]
I thought this tool can extract any mrg files :(. Thank you btw.

**Comment by nickworonekin** [comment]
You're welcome.
