### ISSUE TITLE
Lossless indexed PVR and GVR encoding

### ISSUE THREAD

**Issue by PiKeyAr** [nickworonekin/puyotools#31]
Hi Nick,

Sorry for bombarding your tracker with issues. I've been working on palette support for Texture Editor in [SA Tools](https://github.com/sonicretro/sa_tools) which uses Puyo Tools as a dependency, and I was wondering if you would consider adding a feature to VrSharp's PVM and GVM encoders to create an indexed PVR/GVR from a 16-color or 256-color indexed bitmap without quantization, so that the bitmap's embedded color palette would be treated as the PVR/GVR's palette. This would allow for lossless conversion to Index4/8 if the image is already 16/256 colors, and make it easier to create custom textures for Chao in Sonic Adventure DX and 2(B), which use Index4 PVR and GVR textures.

I tried to implement it myself by modifying Puyo Tools' source code but I couldn't figure it out. If I skip RGBA8888 conversion and quantization in the function [`BitmapToRawIndexed`](https://github.com/nickworonekin/puyotools/blob/5a6e571d05ab2b0a5afbd10a7abcd27ace9f68da/src/VrSharp/Core/VrTextureEncoder.cs#L367) and pass the indexed Bitmap as-is, the resulting texture comes out distorted and I'm not sure why:
![image](https://user-images.githubusercontent.com/23312549/115949713-da464f00-a511-11eb-9aa8-ea3aac5366f3.png)

I'd really appreciate your help, I think supporting this in Puyo Tools would be ideal, but any hints on how to fix it in the code are also much appreciated. Thanks!

**Comment by nickworonekin** [comment]
What if you try skipping the RGBA8888 conversion and quantization, but leave the code regarding BitmapData and copying source to destination? Possible the distorted image could be to stride-related issues.

I was under the assumption that the image would look identical if it had 256 (or less) colors, but if not then it makes sense to just use the provided image palette.

**Comment by PiKeyAr** [comment]
Thanks for the reply. I did keep the code with BitmapData because it is necessary to convert the Bitmap to a byte array before passing it to the encoder. After trying more indexed images I was able to encode several 8-bit textures to PVR, though some of them produced a blank or corrupted texture. I think it has to do with how the built-in palette is set up in some images. I haven't been able to figure out what's happening but it does seem to be caused by having unused colors in the palette. I also couldn't get any indexed GVR conversion to work at all, Texture Encoder just produces nothing even in the original version without my hack.


The issue with 4-bit images I showed earlier may be because `BitmapToRawIndexed` copies the data per pixel and assumes each pixel is 1 byte, which wouldn't work for 16-color indexed images. It also seems that the encoders don't expect pixel data to be smaller than 1 byte, which causes crashes if the data array is adjusted for 4-bit images, which makes it half the expected size. At least that was as far as I got before I gave up trying.


The quantizer replaces the image's original palette with a lower quality version consisting of approximated colors, re-converts to image to 8 bit, and the order of colors doesn't match the original palette. For low fidelity formats like these it takes a pretty big quality hit, apart from making it unusable in the games. Sadly I haven't been able to fix it.

**Comment by nickworonekin** [comment]
I made some changes to `BitmapToRawIndexed` that should address this. With these changes, palletized images use their original palette and aren't quantized unless necessary (for example, going from an 8-bit image to a 4-bit image and there are more than 16 colors in the source). It also adds support for reading 1-bit and 4-bit palletized images.

**Comment by PiKeyAr** [comment]
This is awesome, I tried to encode several indexed bitmaps to PVR and they all worked. I was also able to encode indexed GVR textures though I haven't been able to test them yet.

I have a couple of other suggestions based on the things I found out during my research on paletted textures, but as far as this issue goes, it's resolved. Thank you so much!
