### ISSUE TITLE
Riders PS2 SVR Unable to convert in this format

### ISSUE THREAD

**Issue by Damin72** [nickworonekin/puyotools#36]
Hello! There is some problem with Sonic Riders PS2 textures. This is ARGB8888 with "Index4Argb8Rectangle" data format. But i can't convert to this format edited texture. "Rectangle" just don't work. 4bitIndex convert with glitch, and 8bitIndex convert right, but size of file is drastically bigger. Can you help with them?

**Comment by nickworonekin** [comment]
Can you attach the SVR texture you're replacing and a copy of the texture you're trying to replace it with?

**Comment by Damin72** [comment]
[RidersSVR.zip](https://github.com/nickworonekin/puyotools/files/6757333/RidersSVR.zip)
Sure.

**Comment by nickworonekin** [comment]
Confirmed converting to ARGB8888 using 4-bit Indexed is producing an incorrect/glitched texture.

**Comment by Damin72** [comment]
Welp, i need 4-bit. =)
So i'll be waiting.

**Comment by Damin72** [comment]
[8bitBUG.zip](https://github.com/nickworonekin/puyotools/files/6757418/8bitBUG.zip)
And one more thing. This is 8-bit texture. Yes, PT convert her. Yes, with same size, but when you put converted texture in game. Whoops, game stuck. I put in folder manually created texture (she work in game for sure) and source PNG.

**Comment by nickworonekin** [comment]
This has been fixed as of the most recent commit. Your issue with the 8-bit texture has been addressed too (the SVR data format wasn't being set correctly).

**Comment by Damin72** [comment]
Glad to hear that.

**Comment by Damin72** [comment]
We found problem with swizzle texture. For some reason swizzle-block is 24-30, but no 32. This is can be saw in this texture:
[SwizzleBug.zip](https://github.com/nickworonekin/puyotools/files/6763641/SwizzleBug.zip)

**Comment by Damin72** [comment]
Can confirm those previous fixes works. Only left those swizzle texture. PT can read them and show, but can't convert into original swizzle-format...

**Comment by Damin72** [comment]
Thanks for the new commits! SVR support now work perfectly.
