### ISSUE TITLE
Index out of range when decoding some textures

### ISSUE THREAD

**Issue by piotrek1234** [nickworonekin/puyotools#41]
There are some textures that produce an exception during decoding (even when they were just encoded). I believe this is a problem with encoding, because the game also displays them (encoded ones) incorrectly, and 2.0.4 can't even encode them (nothing is produced).

Exception on decoding is shown only in 2.0.4, 3.0.0-dev just doesn't do anything. Other files work fine.
Encoding settings: texture format `GVR`, data format `8 bit indexed`, palette format `RGB5A3`, `GCIX`

Exception (from 2.0.4):
```
System.IndexOutOfRangeException:
   w VrSharp.GvrTexture.GvrDataCodec.Index8.Decode(Byte[] input, Int32 offset, Int32 width, Int32 height, VrPixelCodec PixelCodec)
   w VrSharp.VrTexture.DecodeTexture()
   w VrSharp.VrTexture.ToBitmap()
   w VrSharp.VrTexture.Save(Stream destination)
   w PuyoTools.Modules.Texture.TextureBase.Read(Stream source)
   w PuyoTools.Texture.Read(Stream source, Bitmap& destination, TextureFormat format)
   w PuyoTools.GUI.TextureViewer.openToolStripMenuItem_Click(Object sender, EventArgs e)
   w System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   w System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   w System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   w System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   w System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   w System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   w System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   w System.Windows.Forms.Control.WndProc(Message& m)
   w System.Windows.Forms.ToolStrip.WndProc(Message& m)
   w System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   w System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Problematic files:
[encoding_problem.zip](https://github.com/nickworonekin/puyotools/files/8854412/encoding_problem.zip)

**Comment by nickworonekin** [comment]
Should now be fixed. I was able to encode then decode the two files you attached using the encoding options you mentioned.

**Comment by piotrek1234** [comment]
Works nicely, thanks.
In the meantime I was using a dirty fix with just filling the pallete with empty, unused colors (so it always has 256 elements), but your solution is much better.
