### ISSUE TITLE
Rare rectangular 4bpp-palletized PVR texture

### ISSUE THREAD

**Issue by IlDucci** [nickworonekin/puyotools#42]
Greetings. A colleague of mine has been using the latest developments in palletized PVR extraction to work on Resident Evil: Code Veronica for Dreamcast. We have managed to extract most of the palletized textures, but there is a particular one that is giving him headaches trying to extract it. It is a 1024x512 4bpp palletized texture that has the unfortunate distinction of being rectangular (and I know that rectangular textures do not allow for fancy stuff in VQ compressions, for example). Could you please help us fully decode this texture?

Here's the files: [OPTION.zip](https://github.com/nickworonekin/puyotools/files/9418288/OPTION.zip)

And this is how it looks like in the PS2 version:
![00000004-TEX1](https://user-images.githubusercontent.com/5641681/186487047-a24f6680-65c9-4feb-aa90-f11414e44c88.png)

**Comment by nickworonekin** [comment]
Should be fixed now. This is the decoded PVR I got from it:

![optionmenu-2](https://user-images.githubusercontent.com/3733290/186994651-2674dc02-c545-477f-9b28-342653bfdddd.png)
.

**Comment by IlDucci** [comment]
Thank you very much! I will send a message to my colleague so he can resume the work we are doing.
