### ISSUE TITLE
There is something wrong with PVR decoder for Skies of Arcadia texture

### ISSUE THREAD

**Issue by Metafalica** [nickworonekin/puyotools#7]
![puyotools pvr crash](https://cloud.githubusercontent.com/assets/5286295/11513773/10684ac8-9886-11e5-981d-f9635fbf2989.png)

It determines this PVR DataFormat as SmallVq and PixelFormat as Argb1555.
There is many PVR files of such format in this game and all crashes your program.

The link for PVR texture: https://www.dropbox.com/s/vq73hkwf7gy1shw/test.pvr?dl=0

**Comment by MainMemory** [comment]
Additionally, there are some textures from Sonic Adventure (DC) in the SmallVq format, which Puyo Tools (and thus my PVMEditSharp program) are unable to render to Bitmaps.
Examples: http://mmbot.reimuhakurei.net/drum_ref.pvr http://mmbot.reimuhakurei.net/drumfuta1.pvr

I don't know if it would help, but we do have access to the C++ source code for Sega's WinPVR tool from the Dreamcast Katana SDK.

**Comment by nickworonekin** [comment]
I can't test those two files, but Puyo Tools should now be able to decode them properly.
