### ISSUE TITLE
Index out of range while decoding texture

### ISSUE THREAD

**Issue by SonicFreak94** [nickworonekin/puyotools#8]
I've attached a set of textures from Sonic Adventure (Dreamcast) that fail to decode:
[broken.zip](https://github.com/nickworonekin/puyotools/files/280714/broken.zip)

It seems to happen in `VrSharp.PvrTexture.PvrPixelCodec.Rgb565.DecodePixel` which is called by `VrSharp.VrPixelCodec.DecodePalette`

**Comment by nickworonekin** [comment]
All these textures now decode correctly in 2.0.2.
